p("Most cancers are named after the part of the body where they start. 'Cancer Type', shown here, is a broad classification that typically encompasses multiple cancers that are within a similar body system, such as all organs related to digestive functions are included in 'Digestive Organs'. 'Cancer Type' categorizes cancers into 19 groups, including 'all cancers' and 'all other unspecified cancers'. For details on the groupings and coding classifications, please see the",
                              tags$a(href="http://www.bccancer.bc.ca/statistics-and-reports-site/Documents/cancer%20definitions%20table_20240910.pdf", target="_blank", "glossary."), tags$br(), tags$br(),"When you select a 'Cancer Type', the multiple cancers it encompasses are listed within 'Cancer Subtype'.")
p("'Cancer Subtype' enables the user to obtain information at a more detailed breakdown of the cancers that fall within similar body systems defined by the 'Cancer Type'. If data is required for the cancer type overall and not at the cancer subtype level then the user can select the 'all' category within 'Cancer Subtype'. For details on the groupings and coding classifications, please see the",
                              tags$a(href="http://www.bccancer.bc.ca/statistics-and-reports-site/Documents/cancer%20definitions%20table_20240910.pdf", target="_blank", "glossary."))
p("Most cancers are named after the part of the body where they start. 'Cancer Type', shown here, groups cancers according to the Canadian Cancer Statistics (CCS) groupings which typically encompasses multiple cancers that are within a similar body system. They are slightly broader than 'Cancer Subtype' but more detailed than 'Cancer Type'. For details on the groupings and coding classifications, please see the",
                              tags$a(href="http://www.bccancer.bc.ca/statistics-and-reports-site/Documents/cancer%20definitions%20table_20240910.pdf", target="_blank", "glossary."))
p("Most cancers are named after the part of the body where they start. 'Cancer Type', shown here, is a broad classification that typically encompasses multiple cancers that are within a similar body system, such as all organs related to digestive functions are included in 'Digestive Organs'. 'Cancer Type' categorizes cancers into 19 groups, including 'all cancers' and 'all other unspecified cancers'. For details on the groupings and coding classifications, please see the",
                              tags$a(href="http://www.bccancer.bc.ca/statistics-and-reports-site/Documents/cancer%20definitions%20table_20240910.pdf", target="_blank", "glossary."), " Note, ‘Lung’ is shown as a cancer type for this app rather than ‘Respiratory System’.", tags$br(), tags$br(),"When you select a 'Cancer Type', the multiple cancers it encompasses are listed within 'Cancer Subtype'.")
p("'Cancer Subtype' enables the user to obtain information at a more detailed breakdown of the cancers that fall within similar body systems defined by the 'Cancer Type'. If data is required for the cancer type overall and not at the cancer subtype level then the user can select the 'all' category within 'Cancer Subtype'. For details on the groupings and coding classifications, please see the",
                              tags$a(href="http://www.bccancer.bc.ca/statistics-and-reports-site/Documents/cancer%20definitions%20table_20240910.pdf", target="_blank", "glossary.")," Note, ‘Respiratory System – Other and Unspecified’ is combined with ‘All Other and Unspecified Cancers’ due to the small number of cases for this subtype of cancer.")
p("Test_website")
